#ifndef CONFIG_H
#define CONFIG_H
#include <colorType.hpp>
#include <ftxui/component/component.hpp>
#include <serializers.hpp>

#define APP_TITLE "weather-cpp"
// TODO: look into paths, this is not good. Look at different OS paths
#define STYLE_CONFIG_LOCATION "/home/cobel/.config/weather-cpp/style.json"

static serializers::colorArray defaultColors = {
    {
        ColorType::TEXT,
        ftxui::Color::RGB(205, 214, 244),
    },
    {
        ColorType::HIGHLIGHT,
        ftxui::Color::RGB(250, 179, 135),
    },
};

static std::unordered_map<std::string, std::string> countryToFlag = {
    {"Ascension Island", "🇦🇨"},
    {"Antarctica", "🇦🇶"},
    {"American Samoa", "🇦🇸"},
    {"Australia", "🇦🇺"},
    {"Åland Islands", "🇦🇽"},
    {"Bouvet Island", "🇧🇻"},
    {"Cocos (Keeling) Islands", "🇨🇨"},
    {"Cook Islands", "🇨🇰"},
    {"Clipperton Island", "🇨🇵"},
    {"Christmas Island", "🇨🇽"},
    {"Diego Garcia", "🇩🇬"},
    {"Fiji", "🇫🇯"},
    {"Micronesia", "🇫🇲"},
    {"Greenland", "🇬🇱"},
    {"South Georgia & South Sandwich Islands", "🇬🇸"},
    {"Guam", "🇬🇺"},
    {"Heard & McDonald Islands", "🇭🇲"},
    {"Canary Islands", "🇮🇨"},
    {"British Indian Ocean Territory", "🇮🇴"},
    {"Kiribati", "🇰🇮"},
    {"Marshall Islands", "🇲🇭"},
    {"Northern Mariana Islands", "🇲🇵"},
    {"New Caledonia", "🇳🇨"},
    {"Norfolk Island", "🇳🇫"},
    {"Nauru", "🇳🇷"},
    {"Niue", "🇳🇺"},
    {"New Zealand", "🇳🇿"},
    {"French Polynesia", "🇵🇫"},
    {"Papua New Guinea", "🇵🇬"},
    {"Pitcairn Islands", "🇵🇳"},
    {"Palau", "🇵🇼"},
    {"Réunion", "🇷🇪"},
    {"Solomon Islands", "🇸🇧"},
    {"St. Helena", "🇸🇭"},
    {"Svalbard & Jan Mayen", "🇸🇯"},
    {"São Tomé & Príncipe", "🇸🇹"},
    {"Tristan Da Cunha", "🇹🇦"},
    {"French Southern Territories", "🇹🇫"},
    {"Tokelau", "🇹🇰"},
    {"Tonga", "🇹🇴"},
    {"Tuvalu", "🇹🇻"},
    {"U.S. Outlying Islands", "🇺🇲"},
    {"St. Vincent & Grenadines", "🇻🇨"},
    {"Vanuatu", "🇻🇺"},
    {"Wallis & Futuna", "🇼🇫"},
    {"Samoa", "🇼🇸"},
    {"Mayotte", "🇾🇹"},
    {"Andorra", "🇦🇩"},
    {"Albania", "🇦🇱"},
    {"Armenia", "🇦🇲"},
    {"Austria", "🇦🇹"},
    {"Bosnia & Herzegovina", "🇧🇦"},
    {"Belgium", "🇧🇪"},
    {"Bulgaria", "🇧🇬"},
    {"Belarus", "🇧🇾"},
    {"Switzerland", "🇨🇭"},
    {"Cyprus", "🇨🇾"},
    {"Czechia", "🇨🇿"},
    {"Germany", "🇩🇪"},
    {"Denmark", "🇩🇰"},
    {"Ceuta & Melilla", "🇪🇦"},
    {"Estonia", "🇪🇪"},
    {"Spain", "🇪🇸"},
    {"European Union", "🇪🇺"},
    {"Finland", "🇫🇮"},
    {"France", "🇫🇷"},
    {"United Kingdom", "🇬🇧"},
    {"Georgia", "🇬🇪"},
    {"Guernsey", "🇬🇬"},
    {"Gibraltar", "🇬🇮"},
    {"Greece", "🇬🇷"},
    {"Croatia", "🇭🇷"},
    {"Hungary", "🇭🇺"},
    {"Ireland", "🇮🇪"},
    {"Isle of Man", "🇮🇲"},
    {"Iceland", "🇮🇸"},
    {"Italy", "🇮🇹"},
    {"Jersey", "🇯🇪"},
    {"Liechtenstein", "🇱🇮"},
    {"Lithuania", "🇱🇹"},
    {"Luxembourg", "🇱🇺"},
    {"Latvia", "🇱🇻"},
    {"Monaco", "🇲🇨"},
    {"Moldova", "🇲🇩"},
    {"Montenegro", "🇲🇪"},
    {"North Macedonia", "🇲🇰"},
    {"Malta", "🇲🇹"},
    {"Netherlands", "🇳🇱"},
    {"Norway", "🇳🇴"},
    {"Poland", "🇵🇱"},
    {"Portugal", "🇵🇹"},
    {"Romania", "🇷🇴"},
    {"Serbia", "🇷🇸"},
    {"Russia", "🇷🇺"},
    {"Sweden", "🇸🇪"},
    {"Slovenia", "🇸🇮"},
    {"Slovakia", "🇸🇰"},
    {"San Marino", "🇸🇲"},
    {"Ukraine", "🇺🇦"},
    {"Vatican City", "🇻🇦"},
    {"Kosovo", "🇽🇰"},
    {"England", "🏴󠁧󠁢󠁥󠁮󠁧󠁿"},
    {"Scotland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"},
    {"Wales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿"},
    {"United Arab Emirates", "🇦🇪"},
    {"Afghanistan", "🇦🇫"},
    {"Azerbaijan", "🇦🇿"},
    {"Bangladesh", "🇧🇩"},
    {"Bahrain", "🇧🇭"},
    {"Brunei", "🇧🇳"},
    {"Bhutan", "🇧🇹"},
    {"China", "🇨🇳"},
    {"Hong Kong SAR China", "🇭🇰"},
    {"Indonesia", "🇮🇩"},
    {"Israel", "🇮🇱"},
    {"India", "🇮🇳"},
    {"Iraq", "🇮🇶"},
    {"Iran", "🇮🇷"},
    {"Jordan", "🇯🇴"},
    {"Japan", "🇯🇵"},
    {"Kyrgyzstan", "🇰🇬"},
    {"Cambodia", "🇰🇭"},
    {"North Korea", "🇰🇵"},
    {"South Korea", "🇰🇷"},
    {"Kuwait", "🇰🇼"},
    {"Kazakhstan", "🇰🇿"},
    {"Laos", "🇱🇦"},
    {"Lebanon", "🇱🇧"},
    {"Sri Lanka", "🇱🇰"},
    {"Myanmar (Burma)", "🇲🇲"},
    {"Mongolia", "🇲🇳"},
    {"Macao Sar China", "🇲🇴"},
    {"Maldives", "🇲🇻"},
    {"Malaysia", "🇲🇾"},
    {"Nepal", "🇳🇵"},
    {"Oman", "🇴🇲"},
    {"Philippines", "🇵🇭"},
    {"Pakistan", "🇵🇰"},
    {"Palestinian Territories", "🇵🇸"},
    {"Qatar", "🇶🇦"},
    {"Russia", "🇷🇺"},
    {"Saudi Arabia", "🇸🇦"},
    {"Singapore", "🇸🇬"},
    {"Syria", "🇸🇾"},
    {"Thailand", "🇹🇭"},
    {"Tajikistan", "🇹🇯"},
    {"Timor-Leste", "🇹🇱"},
    {"Turkmenistan", "🇹🇲"},
    {"Turkey (Türkiye)", "🇹🇷"},
    {"Taiwan", "🇹🇼"},
    {"Uzbekistan", "🇺🇿"},
    {"Vietnam", "🇻🇳"},
    {"Yemen", "🇾🇪"},
    {"Antigua & Barbuda", "🇦🇬"},
    {"Anguilla", "🇦🇮"},
    {"Argentina", "🇦🇷"},
    {"Aruba", "🇦🇼"},
    {"Barbados", "🇧🇧"},
    {"St. Barthélemy", "🇧🇱"},
    {"Bermuda", "🇧🇲"},
    {"Bolivia", "🇧🇴"},
    {"Caribbean Netherlands", "🇧🇶"},
    {"Brazil", "🇧🇷"},
    {"Bahamas", "🇧🇸"},
    {"Belize", "🇧🇿"},
    {"Canada", "🇨🇦"},
    {"Chile", "🇨🇱"},
    {"Colombia", "🇨🇴"},
    {"Costa Rica", "🇨🇷"},
    {"Cuba", "🇨🇺"},
    {"Curaçao", "🇨🇼"},
    {"Dominica", "🇩🇲"},
    {"Dominican Republic", "🇩🇴"},
    {"Ecuador", "🇪🇨"},
    {"Falkland Islands", "🇫🇰"},
    {"Grenada", "🇬🇩"},
    {"French Guiana", "🇬🇫"},
    {"Guadeloupe", "🇬🇵"},
    {"Guatemala", "🇬🇹"},
    {"Guyana", "🇬🇾"},
    {"Honduras", "🇭🇳"},
    {"Haiti", "🇭🇹"},
    {"Jamaica", "🇯🇲"},
    {"St. Kitts & Nevis", "🇰🇳"},
    {"Cayman Islands", "🇰🇾"},
    {"St. Lucia", "🇱🇨"},
    {"St. Martin", "🇲🇫"},
    {"Martinique", "🇲🇶"},
    {"Montserrat", "🇲🇸"},
    {"Mexico", "🇲🇽"},
    {"Nicaragua", "🇳🇮"},
    {"Panama", "🇵🇦"},
    {"Peru", "🇵🇪"},
    {"St. Pierre & Miquelon", "🇵🇲"},
    {"Puerto Rico", "🇵🇷"},
    {"Paraguay", "🇵🇾"},
    {"Suriname", "🇸🇷"},
    {"El Salvador", "🇸🇻"},
    {"Sint Maarten", "🇸🇽"},
    {"Turks & Caicos Islands", "🇹🇨"},
    {"Trinidad & Tobago", "🇹🇹"},
    {"United States", "🇺🇸"},
    {"Uruguay", "🇺🇾"},
    {"Venezuela", "🇻🇪"},
    {"British Virgin Islands", "🇻🇬"},
    {"U.S. Virgin Islands", "🇻🇮"},
    {"Angola", "🇦🇴"},
    {"Burkina Faso", "🇧🇫"},
    {"Burundi", "🇧🇮"},
    {"Benin", "🇧🇯"},
    {"Botswana", "🇧🇼"},
    {"Congo - Kinshasa", "🇨🇩"},
    {"Central African Republic", "🇨🇫"},
    {"Congo - Brazzaville", "🇨🇬"},
    {"Côte d’Ivoire", "🇨🇮"},
    {"Cameroon", "🇨🇲"},
    {"Cape Verde", "🇨🇻"},
    {"Djibouti", "🇩🇯"},
    {"Algeria", "🇩🇿"},
    {"Egypt", "🇪🇬"},
    {"Western Sahara", "🇪🇭"},
    {"Eritrea", "🇪🇷"},
    {"Ethiopia", "🇪🇹"},
    {"Gabon", "🇬🇦"},
    {"Ghana", "🇬🇭"},
    {"Gambia", "🇬🇲"},
    {"Guinea", "🇬🇳"},
    {"Equatorial Guinea", "🇬🇶"},
    {"Guinea-Bissau", "🇬🇼"},
    {"Kenya", "🇰🇪"},
    {"Comoros", "🇰🇲"},
    {"Liberia", "🇱🇷"},
    {"Lesotho", "🇱🇸"},
    {"Libya", "🇱🇾"},
    {"Morocco", "🇲🇦"},
    {"Madagascar", "🇲🇬"},
    {"Mali", "🇲🇱"},
    {"Mauritania", "🇲🇷"},
    {"Mauritius", "🇲🇺"},
    {"Malawi", "🇲🇼"},
    {"Mozambique", "🇲🇿"},
    {"Namibia", "🇳🇦"},
    {"Niger", "🇳🇪"},
    {"Nigeria", "🇳🇬"},
    {"Rwanda", "🇷🇼"},
    {"Seychelles", "🇸🇨"},
    {"Sudan", "🇸🇩"},
    {"Sierra Leone", "🇸🇱"},
    {"Senegal", "🇸🇳"},
    {"Somalia", "🇸🇴"},
    {"South Sudan", "🇸🇸"},
    {"Eswatini", "🇸🇿"},
    {"Chad", "🇹🇩"},
    {"Togo", "🇹🇬"},
    {"Tunisia", "🇹🇳"},
    {"Tanzania", "🇹🇿"},
    {"Uganda", "🇺🇬"},
    {"South Africa", "🇿🇦"},
    {"Zambia", "🇿🇲"},
    {"Zimbabwe", "🇿🇼"},
};

void initializeConfig();

#endif
